# This is a test of the pre-commit hook
In the following cells we will hide some input and output

In [9]:
import numpy  # Nothing hidden here
print(numpy.__version__)

1.23.5


# Input/Output hidden
Only in jupyter-lab, not in jupyterbook

In [10]:
a = numpy.arange(5)
print(a)

[0 1 2 3 4]


# Input/Output hidden
In both jupyterlab and jupyterbook

In [11]:
print(a)

[0 1 2 3 4]


# Only hide input
reference solution can be found below

In [12]:
# Add code here that should get the same solution as below

In [13]:
print(a)

[0 1 2 3 4]
